# ใช้ Node.js เป็น Base Image
FROM node:20

# ตั้งค่า Working Directory
WORKDIR /app

# คัดลอก package.json และ package-lock.json
COPY package*.json ./

# ติดตั้ง Dependencies โดยใช้ cache ของ Docker เพื่อให้การ build เร็วขึ้นในครั้งถัดไป
RUN npm install

# คัดลอกโค้ดทั้งหมดไปยัง container
COPY . .

# เปิดพอร์ต 5173 สำหรับ Vite Development Server
EXPOSE 5173

# เริ่ม Vite Development Server
CMD ["npm", "run", "dev"]
