services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - mynetwork

  frontend:
    image: earth123456789/seniorfrontend:latest
    container_name: seniorlink_frontend_1
    networks:
      - mynetwork
    environment:
      - VITE_API_URL=http://nginx/api

  backend:
    image: earth123456789/seniorbackend:latest
    container_name: seniorlink_backend_1
    networks:
      - mynetwork
    environment:
      POSTGRES_DB: senior_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      ALLOWED_HOSTS: 'nginx,localhost,34.87.118.33'

  db:
    image: postgres
    container_name: seniorlink_db_1
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
