version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # ทำให้ nginx รันบนพอร์ต 80 ของเครื่อง host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - mynetwork

  frontend:
    image: earth123456789/seniorfrontend:latest
    networks:
      - mynetwork

  backend:
    image: earth123456789/seniorbackend:latest
    networks:
      - mynetwork

  db:
    image: postgres
    environment:
      POSTGRES_DB: senior_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
