version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # เปิดพอร์ต 80 เพื่อให้เข้าถึงจากภายนอก
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount nginx.conf ของคุณ
    depends_on:
      - frontend
      - backend
    networks:
      - mynetwork

  frontend:
    image: earth123456789/seniorfrontend:latest
    container_name: seniorlink_frontend_1
    networks:
      - mynetwork

  backend:
    image: earth123456789/seniorbackend:latest
    container_name: seniorlink_backend_1
    networks:
      - mynetwork
    environment:
      POSTGRES_DB: senior_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres
    container_name: seniorlink_db_1
    networks:
      - mynetwork
    environment:
      POSTGRES_DB: senior_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

networks:
  mynetwork:
    driver: bridge
