# Pull base image
FROM python:3.12.0

# Set environment variables
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /code

# Install dependencies
COPY ./requirements.txt . 
RUN pip install --no-cache-dir -r requirements.txt

# ติดตั้ง gunicorn
RUN pip install gunicorn

# Copy project files
COPY . .

# CMD สำหรับการรัน gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]
