# Generated by Django 5.1.2 on 2024-10-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_jobcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
