# Generated by Django 5.1.2 on 2024-10-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_alter_education_end_year_alter_education_start_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
