# Generated by Django 5.1.2 on 2024-10-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_delete_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='health_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='work_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
